
version: '3'

services:

    proj:
        container_name: ${BW_PROJ_NAME}-flask
        image: bazawinner/dev-fovsfe-flask:${BW_DEV_FLASK_VERSION}
        tty: true
        environment:
            - TZ=Europe/Moscow

            # - APP_ROOT=amazing
            - BW_PROJ_NAME
        ports:
            - $BW_DEV_FLASK_PORT:5000
        volumes:
            - ./src/flask:/app
