version: '3'

services:

    proj:
        container_name: prod-${BW_PROJ_NAME}-flask
        # image: bazawinner/prod-fovsfe-flask:1
        image: bazawinner/prod-${BW_PROJ_NAME}-flask:${BW_PROD_FLASK_VERSION}
        tty: true

        environment:
            - TZ=Europe/Moscow
            - BW_PROJ_NAME
            - PORT=3000
        ports:
            - ${BW_PROD_FLASK_PORT}:3000

